name: Poosh
on: 
  push:
   branches:
     - master
    


jobs:
  hello_world_job:
    name: A job to say hello
    runs-on: self-hosted
    steps:
    - name: Hello world action step
      id: hello
      uses: rEz4k/hello-world-javascript-action@v1.1
      with:
        who-to-greet: 'Max the Octocat'
      # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
© 2021 GitHub, Inc.
