name: Poosh
on: [push]
    


jobs:
  hello_world_job:
    name: A job to say hello
    runs-on: ubuntu-latest
    steps:
    - name: Hello world action step
      id: hello
      uses: rEz4k/hello-world-javascript-action@v1.2
      with:
        who-to-greet: 'the Octocat'
      # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"

